title: <p align="center"> Srujan Jogu </p>
logo: /assets/img/srujan_photo.jpg
description: Data Science manager with 11+ years of overall experience
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
